name: Generate QKD Report MD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Packages
        run: pip install arxiv openai

      - name: Run Script to Generate MD file
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: python qkd_tracker.py

      - name: Commit and Push the MD file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add new QKD report MD file"
          branch: main
          file_pattern: '*.md'
